chore: url 이슈대응 -  npm install @types/node
[오류 발생 대응]
1. Cannot find module 'url' or its corresponding type declarations.ts(2307)
2. Property 'url' does not exist on type 'ImportMeta'.ts(2339)